name: Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install

      - uses: ./
        with:
          coveragedir: './src/TestReporter.js'
          coveragepct: 100
          outputfile: 'output.txt'
